
CREATE TABLE groups
(
    groupId         BIGINT AUTO_INCREMENT,
    name            VARCHAR(25) NOT NULL,
    direction       VARCHAR(25),
    startDate       DATE,
    lastUpdatedTime TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    entryTime       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT GROUP_PK PRIMARY KEY (groupId)
);

CREATE TABLE lessons
(
    lessonId    BIGINT AUTO_INCREMENT,
    groupId     BIGINT,
    topic       VARCHAR(30),
    lessonDate  DATETIME,
    materials   VARCHAR(5000),
    lastUpdated TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    entryTime   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT LESSONS_PK PRIMARY KEY (lessonId),
    CONSTRAINT LESSONS_PK_GROUPID_PK FOREIGN KEY (groupId) REFERENCES GROUPS (groupId)
);

CREATE TABLE users
(
    userId          BIGINT AUTO_INCREMENT,
    groupId          BIGINT,
    role            VARCHAR(15),
    firstName       VARCHAR(30) NOT NULL,
    lastName        VARCHAR(30) NOT NULL,
    dateOfBirth     DATE,
    lastUpdatedTime TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    entryTime       TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT USERS_PK PRIMARY KEY (userId),
    CONSTRAINT USERS_PK_GROUPID_PK FOREIGN KEY (groupId) REFERENCES GROUPS (groupId)
);

CREATE TABLE homeTask
(
    hwTaskId    BIGINT AUTO_INCREMENT,
    lessonId    BIGINT,
    task        VARCHAR(3000),
    materials   VARCHAR(5000),
    hwTaskDate  DATE,
    deadLine    DATE,
    lastUpdated TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    entryTime   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT HOMETASK_P PRIMARY KEY (hwTaskId),
    CONSTRAINT HOMETASK_PK_LESSONS_PK FOREIGN KEY (lessonId) REFERENCES LESSONS (lessonId)
);

CREATE TABLE homeWork
(
    homeWorkId      BIGINT AUTO_INCREMENT,
    userId        BIGINT,
    hwTaskId    BIGINT,
    materialsHomeWork  VARCHAR(5000) NOT NULL,
    dateCreate       DATE,
    lastUpdatedTime TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    entryTime       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT HOMEWORK_PK PRIMARY KEY (homeWorkId),
    CONSTRAINT HOMEWORK_PK_STUDENT_PK FOREIGN KEY (userId) REFERENCES USERS (userId),
    CONSTRAINT HOMEWORK_PK_HOMETASK_PK FOREIGN KEY (hwTaskId) REFERENCES HOMETASK (hwTaskId)
);

CREATE TABLE feeds
(
    feedId    BIGINT AUTO_INCREMENT,
    groupId    BIGINT,
    postId     BIGINT,
    lastUpdated TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    entryTime   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FEED_PK PRIMARY KEY (feedId),
    CONSTRAINT FEED_PK_GROUPS_PK FOREIGN KEY (groupId) REFERENCES GROUPS (groupId)
);

CREATE TABLE posts
(
    postId    BIGINT AUTO_INCREMENT,
    feedId    BIGINT,
    text      VARCHAR(5000) NOT NULL,
    author    VARCHAR(64),
    datePosted DATE,
    lastUpdated TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    entryTime   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT POSTS_PK PRIMARY KEY (postId),
    CONSTRAINT POSTS_PK_FEEDS_PK FOREIGN KEY (feedId) REFERENCES FEEDS (feedId)
);